### ISSUE TITLE
Support for ID3v2 with LAME

### ISSUE THREAD

**Issue by psy-q** [ZivaVatra/flac2all#31]
At the moment flac2all does not like genres that don't map to ID3v1 genre IDs when converting to MP3. Couldn't ID3v2 support solve htis?

**Comment by ZivaVatra** [comment]
Possibly, the logic that handles mp3 encoding has not changed much since I first wrote it, which was more than 10 years ago.

Thing is, ID3v2 would be used automatically if any of the fields could not fit in ID3v1, so the only thing it affects is the Genre ID. I am not convinced it is worth the programming effort to support both methods just for the Genre.

**Comment by psy-q** [comment]
Well, the original ID3 genres are very limited, and I noticed when I tried to convert my FLAC collection that almost all of them end up switched to "unknown". I use the genre to organize which group of random stuff gets played when. You don't want a sudden burst of black metal in a series of dreamwave :)

I will poke around a bit, if I'm not mistaken it used to be quite easy to write the same information both to ID3v1 and v2, that could be a starting point to additionally carry over the genre.

**Comment by ZivaVatra** [comment]
The same information is written, just that IDv1 does not support it, so we cannot add it there. IDv2 uses a free form field for Genre, so that is fine. 

I would imagine that disabling IDv1 would be required, and altering the logic to not set "Unknown" if genres are not recognized wold be needed.

**Comment by psy-q** [comment]
If I remember correctly, ID3v2-capable players will usually give precedence to metadata from ID3v2 if found, and files can contain both ID3v2 and ID3v1 at the same time (one goes at the start of the file, the other at the end). Some players can also be configured to take either one or the other.

I'll do some more research. For me it would be nice to have since my player makes random playlists based on genre, and almost all the genres I use don't map to any of the ID3v1 ones, so that would quickly make a very weird (or interesting) playlist :)

**Comment by ZivaVatra** [comment]
Yeah, but I am not talking about the players here, but about lame :)   

I remember writing the mp3 encoding code years ago, and it was a major PITA. If there was an easier way to handle it, I would have done it! 

I think the problem was, that you only have one "--genre" command line option for lame. If you give it one of the ID3v1 valid genres, lame will write an ID3v1 and ID3v2 tag, and all is good in the world. 

However if you give it a custom genre, lame will skip ID3v1 completely and just write ID3v2 on its own, breaking a lot of ID3v1 only players out there (My car radio for one, is only ID3v1 compatible).

Maybe things have changed in the lame encoder, so if you find anything that can solve the above dilemma, it would be great!

**Comment by OctaneTwisted** [comment]
> However if you give it a custom genre, lame will skip ID3v1 completely and just write ID3v2 on its own,

Looks like that's no longer the case. I tested with lame 3.100:
`flac -dc 01.\ Underground\ Resistance\ -\ Electrocuter.flac | lame -V0 --tg "Electro, Techno" --tt Electrocuter --ty 2018 --tl Electro --tn 01 --tc Submerge\ Recordings --ta Underground\ Resistance - test.mp3`
Seems to work as intended. It automatically wrote "Other" for the id3v1 genre tag and kept the one provided by me in the id3v2 tag.

https://i.imgur.com/OhUsesg.png

**Comment by ZivaVatra** [comment]
Nice! That is good news. 
I see lame 3.100 came out in 2017, so it should be the current version used by most systems by now.

This ticket can be re-opened then, and I will see about removing the old mp3 genre selection code for version5. That way we leave the setting of ID3v1 genre to lame itself.

**Comment by ZivaVatra** [comment]
Right, this has been been done. Branch "version5-newlame" holds the code. 

Tests are ongoing on my end, but it seems to be working fine. Once confirmed I will merge into the version5 master branch. 

I will close the ticket now. If you wish to test, please check out the branch mentioned above run. 
If you do come across any issues, feel free to re-open the ticket. 

Thank you, 

ZV.
