### ISSUE TITLE
Program appears to not terminate after transcoding in opus

### ISSUE THREAD

**Issue by rxrxyuki** [ZivaVatra/flac2all#52]
I seem to be at a loss with this issue, I've been using this utility for quite a while now when converting my flac files to vorbis and lately I've been experimenting with transcoding my stuff into opus. The program itself runs as it should, it seems, but after it goes through all of the files it just hangs there for hours and never terminates. I've looked at htop to see whether there's something off but to me it seems that the process is just idle and are not doing anything.

These are the options that I used:

./flac2all/flac2all_pkg/__init__.py opus -o ./outdir/ --opus-options="bitrate 64" ./indir/

I'm also using the issue45 branch of the program but I have also tested this on a separate machine using the version5 branch and both just does this odd behavior.

Any help is appreciated, thanks!

Here are some screenshots of the behavior:
![github_2](https://user-images.githubusercontent.com/16316425/100163792-6ae01b00-2ef1-11eb-8af2-27f899530f6e.png)
![github_1](https://user-images.githubusercontent.com/16316425/100163795-6b78b180-2ef1-11eb-9620-05d262fc619c.png)

**Comment by ZivaVatra** [comment]
Hi, 

Have you tried with the latest version5 branch? I ask because the screenshot output looks like it is from an old version.

I have just run the same command on my test audio, and it excited just fine:

[code]
~#./flac2all(branch:version5)$./flac2all_pkg/__init__.py opus -o ./testoutput/ --opus-options="bitrate 64" ./testinput
UTC~11:49:30: We have 47 tasks
UTC~11:49:30: Waiting for at least one worker to join
UTC~11:49:30: Got worker fed18c17-5554-43df-9510-34d4a566cbb4 ( 1 workers)
UTC~11:49:30: Got worker d9fef41d-136d-4503-820a-4539e2ace1fa ( 2 workers)
UTC~11:49:30: Got worker f6174e86-d622-4f65-ba65-498e8b03c18a ( 3 workers)
UTC~11:49:30: Got worker d4d5e016-1f0c-4f46-a5e7-08bb01388763 ( 4 workers)
[snip...]
UTC~11:51:04: Worker d9fef41d-136d-4503-820a-4539e2ace1fa terminated (2 running)
UTC~11:51:04: n:16.Freddy Marquez - Quiero Despertar~f6174e86-d622-4f65...  	t:opus      	s:SUCCESS   
UTC~11:51:05: Worker f6174e86-d622-4f65-ba65-498e8b03c18a terminated (1 running)
UTC~11:51:05: Worker d4d5e016-1f0c-4f46-a5e7-08bb01388763 terminated (0 running)
UTC~11:51:05: Waiting for local worker to terminate
UTC~11:51:05: input: 47, output: 47
UTC~11:51:05: Writing log file (./testoutput/conversion_results.log)
Done!
[/code]

**Comment by ZivaVatra** [comment]
Apologies for the above, github UI has been broken for me for a few weeks now, so I can't edit/preview posts. 

The fact is that the new versions of flac2all have output that has UUIDs and workers in the output. The old version does not, hence why I suspect you are running an older version.

Please pull latest version5 from this repo, retry and update the ticket.

**Comment by rxrxyuki** [comment]
Hi, thanks for swift reply!

Yes, it appears that I have made a dumb mistake and am not using the version5 branch as well as having ZMQ installed. Once I've done those it all worked beautifully.

Thank you this wonderful program, keep it up!

**Comment by ZivaVatra** [comment]
Hi, no problem. Glad it is all working for you now, and that you find the program useful :-)
